phrase:
  access_token: 27426bdadaa0fb35d16089e958776763ffb93838882e173a2e7bf2692ffc46c6
  project_id: 6e60aa367a312353e7d215da12072618
  push:
    sources:
    - file: ./i18n/l10n/en/translation.json
      params:
        locale_id: en
        file_format: simple_json
  pull:
    targets:
    - file: ./i18n/l10n/<locale_name>/translation.json
      params:
        file_format: simple_json
